const defaultCategories=["Câbles","Générateurs RF","Antennes","Guides d'onde","Connecteurs","Instruments de mesure","Composants passifs","Amplificateurs","Filtres","Accessoires de laboratoire","Projets & expériences"];
const starter=[
{id:1,title:"Analyseur de spectre",category:"Instruments de mesure",price:"—",image:"assets/spectrum.svg",images:[],description:"Instrument de mesure permettant d'observer la puissance des signaux en fonction de la fréquence.",details:["Mesure fréquentielle","Visualisation du spectre","Analyse RF"],extra:["Utilisé pour caractériser les signaux hyperfréquences."]},
{id:2,title:"Antenne cornet",category:"Antennes",price:"—",image:"assets/horn.svg",images:[],description:"Antenne directive utilisée pour les expériences de rayonnement et de propagation.",details:["Antenne directive","Mesures de gain","Propagation"],extra:["Un classique des bancs de mesure hyperfréquences."]},
{id:3,title:"Guide d'onde",category:"Guides d'onde",price:"—",image:"assets/waveguide.svg",images:[],description:"Structure guidant une onde électromagnétique dans la bande des hyperfréquences.",details:["Propagation guidée","Faibles pertes","Bande micro-ondes"],extra:["Élément fondamental des systèmes RF."]},
{id:4,title:"Générateur RF",category:"Générateurs RF",price:"—",image:"assets/generator.svg",images:[],description:"Source de signaux utilisée pour exciter et tester les circuits et dispositifs RF.",details:["Source RF","Réglage de fréquence","Réglage de puissance"],extra:["Permet de créer des signaux de test contrôlés."]},
{id:5,title:"Coupleur directionnel",category:"Composants passifs",price:"—",image:"assets/coupler.svg",images:[],description:"Composant passif permettant d'échantillonner une partie contrôlée d'un signal hyperfréquence.",details:["Couplage","Mesure","Réseaux RF"],extra:["Très utilisé dans les chaînes de mesure."]},
{id:6,title:"Chambre de mesure",category:"Accessoires de laboratoire",price:"—",image:"assets/chamber.svg",images:[],description:"Environnement expérimental dédié à l'observation et à la caractérisation des phénomènes électromagnétiques.",details:["Mesures RF","Isolation","Expérimentation"],extra:["Une zone de travail pensée pour les manipulations."]}
];
function read(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}
function items(){return window.LH_PUBLISHED?.items || read('lh_items',starter)}
function cats(){return window.LH_PUBLISHED?.categories || read('lh_categories',defaultCategories)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const app=document.getElementById('app');
function renderHome(){
 let entered=false,boot=false,filter='Tous',query='';
 function draw(){
  const data=items(), categories=['Tous',...new Set([...cats(),...data.map(x=>x.category)])];
  const visible=data.filter(x=>(filter==='Tous'||x.category===filter)&&((x.title+' '+x.description).toLowerCase().includes(query.toLowerCase())));
  app.innerHTML=`<main class="site"><header class="topbar"><div class="brand"><span class="orb"></span>LABORATOIRE <b>DES HYPERFRÉQUENCES</b></div><div class="live"><i></i> SYSTÈME ACTIF</div></header><section class="hero"><div class="hero-copy"><span class="eyebrow">ESPACE D'EXPLORATION SCIENTIFIQUE</span><h1>Explorer.<br><em>Mesurer.</em><br>Comprendre.</h1><p>Bienvenue dans un espace dédié aux phénomènes électromagnétiques, aux systèmes RF et aux expériences hyperfréquences.</p></div><div class="radar"><div class="radar-ring r1"></div><div class="radar-ring r2"></div><div class="radar-line"></div><span>2.45<br><small>GHz</small></span></div></section><section class="catalog"><div class="section-head"><div><span class="eyebrow">ARCHIVE DU LABORATOIRE</span><h2>Équipements &amp; expériences</h2></div><div class="count">${String(visible.length).padStart(2,'0')} ÉLÉMENTS</div></div><div class="controls"><div class="filters">${categories.map(c=>`<button data-filter="${esc(c)}" class="${filter===c?'active':''}">${esc(c)}</button>`).join('')}</div><input id="search" value="${esc(query)}" placeholder="Rechercher dans le laboratoire..."></div><div class="grid">${visible.map((x,i)=>`<a href="item/?id=${encodeURIComponent(x.id)}" class="card"><div class="card-image"><img src="${esc(x.image||'assets/chamber.svg')}"><span class="index">${String(i+1).padStart(2,'0')}</span><span class="inspect">INSPECTER ↗</span></div><div class="card-body"><span>${esc(x.category)}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div></a>`).join('')}</div></section><footer><span>LABORATOIRE DES HYPERFRÉQUENCES</span><span>RF / MW / ELECTROMAGNETICS</span></footer></main>`;
  app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw()});
  app.querySelector('#search').oninput=e=>{query=e.target.value;draw();const s=app.querySelector('#search');s.focus();s.setSelectionRange(query.length,query.length)};
 }
 function enter(){if(entered)return;entered=true;app.innerHTML=`<main class="site"><div class="boot"><div class="bootbox"><span class="tiny">LAB SYSTEM // ONLINE</span><strong>Êtes-vous prêt à découvrir<br>ce qui se cache dans le laboratoire ?</strong><span class="cursor">_</span></div></div></main>`;setTimeout(draw,1800)}
 app.innerHTML=`<main class="door-scene"><div class="ambient-grid"></div><div class="door-frame"><div class="door"><div class="door-window"><span>RF</span><small>LAB</small></div><div class="door-title">LABORATOIRE<br><b>DES HYPERFRÉQUENCES</b></div><div class="door-status"><i></i> LAB ACCESS / READY</div><div class="handle"></div></div></div><div class="enter-hint">PRESS ENTER · CLICK ANYWHERE · BEGIN EXPLORATION</div></main>`;
 app.querySelector('.door-scene').onclick=enter;window.onkeydown=e=>{if(!entered)enter()};
}
renderHome();
