const starter=[
{id:1,title:"Analyseur de spectre",category:"Instruments de mesure",price:"—",image:"../assets/spectrum.svg",images:[],description:"Instrument de mesure permettant d'observer la puissance des signaux en fonction de la fréquence.",details:["Mesure fréquentielle","Visualisation du spectre","Analyse RF"],extra:["Utilisé pour caractériser les signaux hyperfréquences."]},
{id:2,title:"Antenne cornet",category:"Antennes",price:"—",image:"../assets/horn.svg",images:[],description:"Antenne directive utilisée pour les expériences de rayonnement et de propagation.",details:["Antenne directive","Mesures de gain","Propagation"],extra:["Un classique des bancs de mesure hyperfréquences."]},
{id:3,title:"Guide d'onde",category:"Guides d'onde",price:"—",image:"../assets/waveguide.svg",images:[],description:"Structure guidant une onde électromagnétique dans la bande des hyperfréquences.",details:["Propagation guidée","Faibles pertes","Bande micro-ondes"],extra:["Élément fondamental des systèmes RF."]},
{id:4,title:"Générateur RF",category:"Générateurs RF",price:"—",image:"../assets/generator.svg",images:[],description:"Source de signaux utilisée pour exciter et tester les circuits et dispositifs RF.",details:["Source RF","Réglage de fréquence","Réglage de puissance"],extra:["Permet de créer des signaux de test contrôlés."]},
{id:5,title:"Coupleur directionnel",category:"Composants passifs",price:"—",image:"../assets/coupler.svg",images:[],description:"Composant passif permettant d'échantillonner une partie contrôlée d'un signal hyperfréquence.",details:["Couplage","Mesure","Réseaux RF"],extra:["Très utilisé dans les chaînes de mesure."]},
{id:6,title:"Chambre de mesure",category:"Accessoires de laboratoire",price:"—",image:"../assets/chamber.svg",images:[],description:"Environnement expérimental dédié à l'observation et à la caractérisation des phénomènes électromagnétiques.",details:["Mesures RF","Isolation","Expérimentation"],extra:["Une zone de travail pensée pour les manipulations."]}
];
function read(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const id=new URLSearchParams(location.search).get('id');const data=window.LH_PUBLISHED?.items || read('lh_items',starter);const x=data.find(a=>String(a.id)===String(id));const app=document.getElementById('app');
if(!x){app.innerHTML='<main class="detail"><header class="topbar"><a class="back" href="../">← RETOUR AU LABORATOIRE</a></header><div class="detail-copy"><h1>Équipement introuvable</h1><p class="lead">Cette fiche n’existe pas.</p></div></main>'}else{app.innerHTML=`<main class="detail"><header class="topbar"><a class="back" href="../">← RETOUR AU LABORATOIRE</a><div class="brand"><span class="orb"></span>LABORATOIRE <b>DES HYPERFRÉQUENCES</b></div></header><div class="detail-wrap"><div class="detail-image"><img src="${esc(x.image||'../assets/chamber.svg')}"><span>${esc(x.category)}</span></div><div class="detail-copy"><span class="eyebrow">FICHE ÉQUIPEMENT</span><h1>${esc(x.title)}</h1><div class="line"></div><p class="lead">${esc(x.description||'')}</p><h4>DONNÉES TECHNIQUES</h4><div class="facts">${(x.details||[]).filter(Boolean).map((d,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span>${esc(d)}</div>`).join('')}</div>${x.price?`<div class="price">${esc(x.price)}</div>`:''}${(x.extra||[]).filter(Boolean).length?`<h4>NOTES</h4><p class="lead">${(x.extra||[]).filter(Boolean).map(esc).join('<br>')}</p>`:''}</div></div>${(x.images||[]).length?`<div class="detail-gallery">${x.images.map(im=>`<img src="${esc(im)}">`).join('')}</div>`:''}</main>`}
