const defaultCategories=["Câbles","Générateurs RF","Antennes","Guides d'onde","Connecteurs","Instruments de mesure","Composants passifs","Amplificateurs","Filtres","Accessoires de laboratoire","Projets & expériences"];
const starter=[
{id:1,title:"Analyseur de spectre",category:"Instruments de mesure",price:"—",image:"../assets/spectrum.svg",images:[],description:"Instrument de mesure permettant d'observer la puissance des signaux en fonction de la fréquence.",details:["Mesure fréquentielle","Visualisation du spectre","Analyse RF"],extra:["Utilisé pour caractériser les signaux hyperfréquences."]},
{id:2,title:"Antenne cornet",category:"Antennes",price:"—",image:"../assets/horn.svg",images:[],description:"Antenne directive utilisée pour les expériences de rayonnement et de propagation.",details:["Antenne directive","Mesures de gain","Propagation"],extra:["Un classique des bancs de mesure hyperfréquences."]},
{id:3,title:"Guide d'onde",category:"Guides d'onde",price:"—",image:"../assets/waveguide.svg",images:[],description:"Structure guidant une onde électromagnétique dans la bande des hyperfréquences.",details:["Propagation guidée","Faibles pertes","Bande micro-ondes"],extra:["Élément fondamental des systèmes RF."]},
{id:4,title:"Générateur RF",category:"Générateurs RF",price:"—",image:"../assets/generator.svg",images:[],description:"Source de signaux utilisée pour exciter et tester les circuits et dispositifs RF.",details:["Source RF","Réglage de fréquence","Réglage de puissance"],extra:["Permet de créer des signaux de test contrôlés."]},
{id:5,title:"Coupleur directionnel",category:"Composants passifs",price:"—",image:"../assets/coupler.svg",images:[],description:"Composant passif permettant d'échantillonner une partie contrôlée d'un signal hyperfréquence.",details:["Couplage","Mesure","Réseaux RF"],extra:["Très utilisé dans les chaînes de mesure."]},
{id:6,title:"Chambre de mesure",category:"Accessoires de laboratoire",price:"—",image:"../assets/chamber.svg",images:[],description:"Environnement expérimental dédié à l'observation et à la caractérisation des phénomènes électromagnétiques.",details:["Mesures RF","Isolation","Expérimentation"],extra:["Une zone de travail pensée pour les manipulations."]}
];
const app=document.getElementById('app');let logged=sessionStorage.getItem('lh_admin')==='1';let items=read('lh_items',starter),cats=read('lh_categories',defaultCategories),selected='Tous',editing=null,msg='';
function read(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}function save(){localStorage.setItem('lh_items',JSON.stringify(items));localStorage.setItem('lh_categories',JSON.stringify(cats))}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(t){msg=t;draw();setTimeout(()=>{msg='';draw()},1700)}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.82))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function login(){app.innerHTML=`<main class="admin-login"><form id="login"><span class="eyebrow">LABORATORY CONTROL</span><h1>Administration</h1><p>Accès au système de gestion du laboratoire.</p><input id="u" placeholder="Nom d'utilisateur"><input id="p" type="password" placeholder="Mot de passe"><button>ACCÉDER AU DASHBOARD</button><small id="err"></small></form></main>`;document.getElementById('login').onsubmit=e=>{e.preventDefault();if(document.getElementById('u').value==='admin'&&document.getElementById('p').value==='admin 123'){sessionStorage.setItem('lh_admin','1');logged=true;draw()}else document.getElementById('err').textContent='Identifiants incorrects.'}}
function add(){editing={id:Date.now(),title:'',category:cats[0]||'Câbles',price:'',image:'',images:[],description:'',details:[''],extra:['']};draw()}
function delItem(id){if(confirm('Supprimer cet élément ?')){items=items.filter(x=>x.id!==id);save();toast('Élément supprimé.')}}
function addCat(){const c=prompt('Nom de la catégorie :');if(c&&c.trim()&&!cats.includes(c.trim())){cats.push(c.trim());save();toast('Catégorie ajoutée.')}}
function delCat(c){if(confirm(`Supprimer la catégorie « ${c} » ? Les éléments restent dans le catalogue.`)){cats=cats.filter(x=>x!==c);save();if(selected===c)selected='Tous';toast('Catégorie supprimée.')}}
function edit(x){editing=JSON.parse(JSON.stringify(x));draw()}
function publish(){
 const payload={version:1,generatedAt:new Date().toISOString(),categories:cats,items:items};
 const blob=new Blob(['window.LH_PUBLISHED='+JSON.stringify(payload)+';'],{type:'text/javascript'});
 const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='catalog.js';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('catalog.js téléchargé. Importez-le à la racine GitHub pour publier.');
}
function draw(){if(!logged){login();return}const shown=selected==='Tous'?items:items.filter(x=>x.category===selected);app.innerHTML=`<main class="dashboard"><aside><div class="dashbrand"><span class="orb"></span> LH <b>CONTROL</b></div><nav><button class="${selected==='Tous'?'navselected':''}" id="all">▦ Tous les éléments</button><button id="new">＋ Nouvel élément</button><button id="newcat">＋ Nouvelle catégorie</button><button id="publish">⇩ Publier le catalogue</button></nav><div class="cat-side"><small>CATÉGORIES</small>${cats.map(c=>`<div><button class="${selected===c?'catselected':''}" data-cat="${esc(c)}">${esc(c)}</button><button class="xcat" data-delcat="${esc(c)}">×</button></div>`).join('')}</div><button class="logout" id="logout">DÉCONNEXION</button></aside><section class="dashmain"><header><div><span class="eyebrow">LABORATOIRE / ADMINISTRATION</span><h1>${selected==='Tous'?'Tableau de bord':esc(selected)}</h1></div><button id="new2">+ NOUVEL ÉLÉMENT</button></header><div class="stats"><div><small>ÉLÉMENTS</small><strong>${items.length}</strong></div><div><small>CATÉGORIES</small><strong>${cats.length}</strong></div><div><small>ÉTAT DU SYSTÈME</small><strong class="ok">ONLINE</strong></div></div>${msg?`<div class="toast">${esc(msg)}</div>`:''}<div class="dashhead"><h2>${selected==='Tous'?'Collection':'Éléments · '+esc(selected)}</h2><span class="muted">${shown.length} élément(s)</span></div><div class="admin-grid">${shown.map(x=>`<article><img src="${esc(x.image||'../assets/chamber.svg')}"><div><span>${esc(x.category)}</span><h3>${esc(x.title||'Sans titre')}</h3><p>${esc(x.description||'Aucune description.')}</p><button data-edit="${x.id}">MODIFIER</button><button class="danger" data-delete="${x.id}">SUPPRIMER</button></div></article>`).join('')}</div></section>${editing?modal():''}</main>`;
 document.getElementById('all').onclick=()=>{selected='Tous';draw()};document.getElementById('new').onclick=add;document.getElementById('new2').onclick=add;document.getElementById('newcat').onclick=addCat;document.getElementById('publish').onclick=publish;document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('lh_admin');logged=false;draw()};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selected=b.dataset.cat;draw()});document.querySelectorAll('[data-delcat]').forEach(b=>b.onclick=()=>delCat(b.dataset.delcat));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(items.find(x=>String(x.id)===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>delItem(Number(b.dataset.delete)));
 if(editing)bindModal();}
function modal(){return `<div class="modal"><form id="itemform"><button type="button" class="close" id="close">×</button><span class="eyebrow">FICHE ÉQUIPEMENT</span><h2>${items.some(x=>x.id===editing.id)?'Modifier':'Ajouter'}</h2><label>Nom / titre<input id="title" required value="${esc(editing.title)}"></label><label>Catégorie<select id="category">${cats.map(c=>`<option ${c===editing.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Image principale <input id="mainimg" type="file" accept="image/*"></label>${editing.image?`<img class="preview" src="${esc(editing.image)}">`:''}<label>Images supplémentaires <input id="extraimgs" type="file" accept="image/*" multiple></label><div class="thumbs">${(editing.images||[]).map((im,i)=>`<div><img src="${esc(im)}"><button type="button" data-rm="${i}">×</button></div>`).join('')}</div><label>Prix / valeur<input id="price" value="${esc(editing.price||'')}" placeholder="Ex. 250 TND"></label><label>Description<textarea id="description">${esc(editing.description||'')}</textarea></label><label>Données / caractéristiques <small>(une ligne = une caractéristique)</small><textarea id="details">${esc((editing.details||[]).join('\n'))}</textarea></label><label>Notes supplémentaires <small>(texte libre)</small><textarea id="extra">${esc((editing.extra||[]).join('\n'))}</textarea></label><button class="save">ENREGISTRER LA FICHE</button></form></div>`}
function bindModal(){document.getElementById('close').onclick=()=>{editing=null;draw()};document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{editing.images.splice(Number(b.dataset.rm),1);draw()});document.getElementById('itemform').onsubmit=async e=>{e.preventDefault();const main=document.getElementById('mainimg').files[0];const more=[...document.getElementById('extraimgs').files];if(main)editing.image=await compress(main);if(more.length){const arr=[];for(const f of more)arr.push(await compress(f));editing.images=[...(editing.images||[]),...arr]}editing.title=document.getElementById('title').value;editing.category=document.getElementById('category').value;editing.price=document.getElementById('price').value;editing.description=document.getElementById('description').value;editing.details=document.getElementById('details').value.split('\n').filter(Boolean);editing.extra=document.getElementById('extra').value.split('\n').filter(Boolean);const idx=items.findIndex(x=>x.id===editing.id);if(idx>=0)items[idx]=editing;else items.push(editing);save();editing=null;toast('Élément enregistré.')}}
draw();
